# Not condition on start and end point
import torch
import h5py
import math
import torch.optim as optim
import torch.nn as nn
import numpy as np
import os
from torch.utils.data import Dataset, DataLoader
from tqdm import tqdm
import glob
# Flow Matching API imports:
from flow_matching.path.scheduler import CondOTScheduler
from flow_matching.path import AffineProbPath
from flow_matching.solver import Solver, ODESolver
from flow_matching.utils import ModelWrapper
from torch.distributions import Independent, Normal
import matplotlib.pyplot as plt
torch.manual_seed(42)


class Flow(nn.Module):
    def __init__(self, dim, hidden_dim=2048):  #hidden_dim=600
        """
        Args:
            dim (int): Dimensionality of the input (observation + flattened actions).
            hidden_dim (int): Number of hidden units.
        """
        super(Flow, self).__init__()
        self.net = nn.Sequential(
            nn.Linear(dim + 1, hidden_dim), nn.ELU(),
            nn.Linear(hidden_dim, hidden_dim), nn.ELU(),
            nn.Linear(hidden_dim, hidden_dim), nn.ELU(),
            nn.Linear(hidden_dim, dim)
        )
    
    def forward(self, x, t):
        # x: (..., T, D), t: (T,) or (batch, T) or (...)
        # ensure t has same leading dims as x, then one trailing dim
        # desired shape for t: x.shape[:-1] + [1]
        target_shape = list(x.shape[:-1]) + [1]             # e.g. [batch, T, 1]
        
        # first, make t a tensor
        if not torch.is_tensor(t):
            t = torch.tensor(t, device=x.device)
        
        # unsqueeze up to rank-1
        while t.dim() < x.dim() - 1:
            t = t.unsqueeze(0)                             # prepend dims
        # now t.dim() == x.dim()-1; e.g. t is [batch, T] or [T]
        
        # add the final time-dim
        t = t.unsqueeze(-1)                                # [..., T, 1]
        
        # expand to match x’s batch/time dims
        t = t.expand(*target_shape)
        
        # concat time channel in front of features
        xt = torch.cat([t, x], dim=-1)                     # [..., T, D+1]
        return self.net(xt)

class DiffuserTrajectoryDataset(Dataset):
    """
    Loads .npz episodes generated by the Diffuser rollout logger.
    split: 'succ', 'fail', or None for both.
    """
    def __init__(self, root_dir, split=None, transform=None):
        pattern = '*_succ.npz' if split=='succ' else '*_fail.npz' if split=='fail' else '*.npz'
        self.files = sorted(glob.glob(os.path.join(root_dir, pattern)))
        if not self.files:
            raise RuntimeError(f"No .npz files found in {root_dir} with split={split}")
        self.transform = transform

        # Peek at first file to get dims
        sample = np.load(self.files[0])
        self.state_dim  = sample['state'].shape[1]
        self.action_dim = sample['action'].shape[1]

    def __len__(self):
        return len(self.files)

    def __getitem__(self, idx):
        data = np.load(self.files[idx])
        # shape (T, D)
        states     = torch.from_numpy(data['state'])      # (T, state_dim)
        actions    = torch.from_numpy(data['action'])     # (T, action_dim)
        next_states= torch.from_numpy(data['next_state']) # (T, state_dim)
        # optionally you could also return rewards, dones
        sample = {
            'state':      states,
            'action':     actions,
            'next_state': next_states,
        }
        if self.transform:
            sample = self.transform(sample)
        return sample

    def dims(self):
        return self.state_dim, self.action_dim


def train(use_action=False,traj_root = "/home/haoran-zhang/Desktop/projects/guardiff/trajectories"):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Training on device: {device}")
    dataset    = DiffuserTrajectoryDataset(traj_root, split='succ')
    state_dim, action_dim = dataset.dims()
    D = state_dim + action_dim
    # Initialize the CNF model with the proper input dimension.
    model = Flow(dim=D).to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)
    dataloader = DataLoader(dataset, batch_size=128, shuffle=True, num_workers=4, collate_fn=lambda x: x)
    # collate_fn=lambda x: x keeps the episode dimension (list of samples), you can flatten later

    path  = AffineProbPath(scheduler=CondOTScheduler())
    num_epochs = 3000

    for epoch in range(num_epochs):
        epoch_loss = 0.0
        pbar = tqdm(dataloader, desc=f"Epoch {epoch+1}/{num_epochs}")
        for batch in pbar:
            # batch is a list of samples (each with sequences of length T)
            # flatten across time: we want (B*T, D) tensors for x0,x1
            states     = torch.cat([s['state']     for s in batch], dim=0).to(device)  # (sum T, state_dim)
            actions    = torch.cat([s['action']    for s in batch], dim=0).to(device)  # (sum T, action_dim)
            next_states= torch.cat([s['next_state']for s in batch], dim=0).to(device)

            x1 = torch.cat([states, actions], dim=-1)  # (N, D)
            x0 = torch.randn_like(x1)                  # (N, D)
            t  = torch.rand(x1.size(0), device=device)

            path_sample = path.sample(t=t, x_0=x0, x_1=x1)
            loss = (model(path_sample.x_t, path_sample.t) - path_sample.dx_t).pow(2).mean()

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            epoch_loss += loss.item()
            pbar.set_postfix(loss=f"{loss.item():.4f}")

        print(f"Epoch {epoch+1}, Avg Loss: {epoch_loss/len(dataloader):.4f}")

        # save periodic checkpoints
        if (epoch+1) % 200 == 0:
            torch.save(model.state_dict(), f"checkpoint_epoch_{epoch+1}.pth")

    return model



# def evaluate_with_odesolver_npz(
#     model,
#     traj_root,
#     split=None,         # 'succ', 'fail', or None for all
#     num_acc=10,
#     step_size=0.001,
#     batch_size=256,
#     device=None
# ):
#     """
#     Evaluate `model` on .npz trajectory data under ODE likelihood.
    
#     Args:
#         model: a Flow network instance, already .to(device) and eval().
#         traj_root (str): directory containing ep_****_succ.npz / fail.npz.
#         split (str): 'succ' | 'fail' | None to select which files.
#         num_acc (int): Hutchinson estimator repeats.
#         step_size (float): ODE solver step size.
#         batch_size (int): how many timesteps per batch.
#         device: torch device (defaults to cuda if available).
#     Returns:
#         mean_ll_est (float): average estimated log-likelihood over all samples.
#     """
#     device = device or torch.device("cuda" if torch.cuda.is_available() else "cpu")
#     model  = model.to(device).eval()
#     wrapped = ModelWrapper(model)
#     solver  = ODESolver(velocity_model=wrapped)

#     # load dataset of full trajectories, splitting succ/fail if requested
#     dataset = DiffuserTrajectoryDataset(traj_root, split=split)
#     state_dim, action_dim = dataset.dims()
#     D = state_dim + action_dim

#     # We need to flatten across time, so collate into lists then cat
#     loader = DataLoader(dataset, batch_size=1, shuffle=False, num_workers=4)

#     all_ll = []
#     with torch.no_grad():
#         pbar = tqdm(loader, desc=f"Eval split={split}")
#         for ep_batch in pbar:
#             # ep_batch is a list of length 1, but DataLoader wraps dims: batch size 1
#             # so we extract sample dict directly:
#             sample = ep_batch[0] if isinstance(ep_batch, list) else ep_batch
#             states  = sample['state'].to(device)      # (T, state_dim)
#             actions = sample['action'].to(device)     # (T, action_dim)
#             # flatten across time:
#             x1 = torch.cat([states, actions], dim=-1)  # (T, D)
#             # compute batch-wise likelihood
#             # base density:
#             base_dist = Independent(
#                 Normal(torch.zeros(D,device=device), torch.ones(D,device=device)),1
#             ).log_prob

#             # repeat Hutchinson
#             ll_acc = 0.0
#             for _ in range(num_acc):
#                 x0 = torch.randn_like(x1)
#                 t  = torch.rand(x1.size(0), device=device)
#                 _, ll = solver.compute_likelihood(
#                     x_1=x1,
#                     method='midpoint',
#                     step_size=step_size,
#                     exact_divergence=False,
#                     log_p0=base_dist
#                 )
#                 ll_acc += ll
#             ll_acc /= num_acc

#             all_ll.append(ll_acc.cpu())

#             pbar.set_postfix(mean_ll=f"{ll_acc.mean().item():.3f}")

#     all_ll = torch.cat(all_ll, dim=0)
#     mean_ll = all_ll.mean().item()
#     return mean_ll

def eval_traj_ll_vector(
    model, 
    traj_path, 
    num_acc=10, 
    step_size=0.001, 
    device=None
):
    """
    Compute a vector of log-likelihoods at each time-step for one trajectory.

    Args:
        model: Flow network, already on `device` and in eval() mode.
        traj_path (str): Path to one .npz file with keys 'state','action'.
        num_acc (int): Number of Hutchinson repetitions.
        step_size (float): ODE solver step size.
        device: torch device (default cuda if available).

    Returns:
        ll_vec (np.ndarray of shape (T,)): mean log-likelihood per time-step.
    """
    device = device or torch.device("cuda" if torch.cuda.is_available() else "cpu")
    wrapped = ModelWrapper(model)
    solver  = ODESolver(velocity_model=wrapped)

    # --- load one trajectory ---
    data   = np.load(traj_path)
    states = torch.from_numpy(data['state']).to(device)    # (T, S)
    actions= torch.from_numpy(data['action']).to(device)   # (T, A)
    x1     = torch.cat([states, actions], dim=-1)          # (T, D)
    D      = x1.shape[-1]

    # base density for CNF likelihood
    base_dist = Independent(Normal(
        torch.zeros(D, device=device),
        torch.ones(D,  device=device)
    ), 1).log_prob

    # accumulate per-step LLm
    ll_acc = torch.zeros(x1.size(0), device=device)  # (T,)
    with torch.no_grad():
        for _ in range(num_acc):
            # sample random initial point and times
            x0 = torch.randn_like(x1)
            t  = torch.rand(x1.size(0), device=device)
            # compute vector of log-likelihoods at each time-step
            _, ll = solver.compute_likelihood(
                x_1            = x1,
                method         = 'midpoint',
                step_size      = step_size,
                exact_divergence = False,
                log_p0         = base_dist
            )
            ll_acc += ll  # ll has shape (T,)
    ll_vec = (ll_acc / num_acc).cpu().numpy()  # average over Hutchinson

    return ll_vec

if __name__ == "__main__":
    # Optionally check dataset details
    full_dataset = DiffuserTrajectoryDataset(root_dir = "/home/haoran-zhang/Desktop/projects/guardiff/trajectories",split = 'succ')
    print("Full t_sc Dataset length:", len(full_dataset))
    print("Dataset dim:", full_dataset.dims())
    print("Dataset sample:", full_dataset[0])
    
    # Train the model using only 80% of the t_sc data.
    #model = train()
    state_dim, action_dim = full_dataset.dims()
    D = state_dim + action_dim
    # Optionally reload a saved model checkpoint
    reload_flag = True
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    reload_path = "/home/haoran-zhang/Desktop/projects/guardiff/checkpoint_epoch_3000.pth"
    traj_root = "/home/haoran-zhang/Desktop/projects/guardiff/trajectories"
    if reload_flag:
        model = Flow(dim=D).to(device)
        model.load_state_dict(torch.load(reload_path))
    model.eval()

    traj_file = "/home/haoran-zhang/Desktop/projects/guardiff/trajectories/ep_0000_succ.npz"
    ll_vec = eval_traj_ll_vector(model, traj_file)

    plt.figure(figsize=(8,4))
    plt.plot(ll_vec, label="log-likelihood")
    plt.xlabel("Time step")
    plt.ylabel("Log-Likelihood (nats)")
    plt.title("Trajectory log-likelihood over time")
    plt.legend()
    plt.grid(True)
    plt.show()

    # succ_ll = evaluate_with_odesolver_npz(model, traj_root, split='succ')
    # fail_ll = evaluate_with_odesolver_npz(model, traj_root, split='fail')
    # print(f"Success LL: {succ_ll:.3f}, Failure LL: {fail_ll:.3f}")
        
    # print("=== Evaluation Results ===")
    # print("Success (In-distribution, validation split) Data:")
    # print("  Estimated Likelihood:", succ_ll)
    # print("Failure (Out-of-distribution) Data:")
    # print("  Estimated Likelihood:", fail_ll)